### ISSUE TITLE
json is not valid 

### ISSUE THREAD

**Issue by janakkkafle** [Prabesh01/nepalstock-api#1]
all data in json are inside apostrophe (')  but it should be in double quote (")
 for example :  market open gives `{'isOpen': 'CLOSE', 'asOf': '2023-01-23T15:00:00', 'id': 80}` this json but it should be
```
 {
"isOpen": "CLOSED",
"asOf": "2023-01-23T15:00:00",
"id": 80
}
```

Thank you .

**Comment by Prabesh01** [comment]
ae607a5839ac957526cadab3d3e0ec7c8fc45e03 should fix it
